using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotelManagmentSys.Models
{
    class Reservation
    {
        public int ReservationId { get; set; } // PK, auto-generated by DB
        public int CustomerId { get; set; } // FK to Customer table
        public int RoomId { get; set; }     // FK to Room table
        public DateTime CheckInDate { get; set; }
        public DateTime CheckOutDate { get; set; }
        public decimal TotalPayment { get; set; } // To store the calculated payment
        public string ReservationStatus { get; set; } // e.g., 'Confirmed', 'Pending', 'Cancelled'

    }
}
